# Exported from Render on 2025-05-10T18:31:55Z
services:
  # Backend API Service
  - type: web
    name: nsu-scheduler-api
    runtime: python
    repo: https://github.com/mustavikhan05/course-finder
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn 'app:create_app()' --bind=0.0.0.0:$PORT
    rootDir: backend
    envVars:
      - key: PYTHONUNBUFFERED
        value: true

  # Frontend Static Site
  - type: web
    name: nsu-scheduler-frontend
    runtime: static
    repo: https://github.com/mustavikhan05/course-finder
    envVars:
      - key: REACT_APP_API_URL
        sync: false
    buildCommand: npm install && npm run build
    staticPublishPath: build
    rootDir: frontend

version: "1" 